# The URL the site will be built for
base_url = "https://metta.systems"
title = "Metta"
description = "decentralized internets"

theme = "hyde-x"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

highlight_code = true
highlight_theme = "ayu-dark"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true
default_language = "en"

taxonomies = [
    {name = "categories", paginate_by = 15},
]

generate_rss = true

[extra]
# Put all your custom variables here
#description = "Status updates on Metta development"
#paginate = 15
#highlight = "zenburn" -- if using hljs
#tagline = "decentralized internets"
#truncate = true # Zola doesn't use this setting
languageCode = "en"

utterances = "metta-systems/metta.systems"
utterancesMapping = "url"
utterancesTheme = "github-light"

hyde_theme = "theme-base-0e"
hyde_reverse = false
hyde_links = [
    {url = "/", name = "Blog"},
    {url = "/misc/manifesto", name = "Manifesto"},
]

googleAnalytics = "UA-45168329-1"

hydex_github = "https://github.com/metta-systems"

# Optional additional custom CSS file URL, will override other styles.
customCSS = "/css/overrides.css"

# Default page metadata, used when the specific page doesn't set its own.
defaultKeywords = "devlog,blog,metta,decentralised,peer-to-peer,vesper,rust"
